.PHONY: clean

pottery: pottery.done

pottery.done: 
	@echo pottery
	@type nul > pottery.done

irrigation: irrigation.done

irrigation.done: pottery.done
	@echo irrigation
	@type nul > irrigation.done

writing: writing.done

writing.done: pottery.done
	@echo writing
	@type nul > writing.done

animal_husbandry: animal_husbandry.done

animal_husbandry.done: 
	@echo animal_husbandry
	@type nul > animal_husbandry.done

archery: archery.done

archery.done: animal_husbandry.done
	@echo archery
	@type nul > archery.done

mining: mining.done

mining.done: 
	@echo mining
	@type nul > mining.done

masonry: masonry.done

masonry.done: mining.done
	@echo masonry
	@type nul > masonry.done

bronze_working: bronze_working.done

bronze_working.done: mining.done
	@echo bronze_working
	@type nul > bronze_working.done

the_wheel: the_wheel.done

the_wheel.done: mining.done
	@echo the_wheel
	@type nul > the_wheel.done

apprenticeship: apprenticeship.done

apprenticeship.done: mining.done currency.done horseback_riding.done
	@echo apprenticeship
	@type nul > apprenticeship.done

sailing: sailing.done

sailing.done: 
	@echo sailing
	@type nul > sailing.done

celestial_navigation: celestial_navigation.done

celestial_navigation.done: sailing.done astrology.done
	@echo celestial_navigation
	@type nul > celestial_navigation.done

shipbuilding: shipbuilding.done

shipbuilding.done: sailing.done
	@echo shipbuilding
	@type nul > shipbuilding.done

astrology: astrology.done

astrology.done: 
	@echo astrology
	@type nul > astrology.done

drama_poetry: drama_poetry.done

drama_poetry.done: astrology.done irrigation.done masonry.done early_empire.done mysticism.done
	@echo drama_poetry
	@type nul > drama_poetry.done

theology: theology.done

theology.done: astrology.done mysticism.done drama_poetry.done
	@echo theology
	@type nul > theology.done

horseback_riding: horseback_riding.done

horseback_riding.done: archery.done
	@echo horseback_riding
	@type nul > horseback_riding.done

machinery: machinery.done

machinery.done: archery.done iron_working.done engineering.done
	@echo machinery
	@type nul > machinery.done

currency: currency.done

currency.done: writing.done foreign_trade.done
	@echo currency
	@type nul > currency.done

state_workforce: state_workforce.done

state_workforce.done: writing.done bronze_working.done craftsmanship.done
	@echo state_workforce
	@type nul > state_workforce.done

recorded_history: recorded_history.done

recorded_history.done: writing.done political_philosophy.done drama_poetry.done
	@echo recorded_history
	@type nul > recorded_history.done

construction: construction.done

construction.done: masonry.done the_wheel.done horseback_riding.done
	@echo construction
	@type nul > construction.done

engineering: engineering.done

engineering.done: masonry.done the_wheel.done
	@echo engineering
	@type nul > engineering.done

iron_working: iron_working.done

iron_working.done: bronze_working.done
	@echo iron_working
	@type nul > iron_working.done

mathematics: mathematics.done

mathematics.done: bronze_working.done celestial_navigation.done currency.done drama_poetry.done
	@echo mathematics
	@type nul > mathematics.done

military_training: military_training.done

military_training.done: bronze_working.done military_tradition.done games_recreation.done
	@echo military_training
	@type nul > military_training.done

cartography: cartography.done

cartography.done: celestial_navigation.done shipbuilding.done
	@echo cartography
	@type nul > cartography.done

medieval_faires: medieval_faires.done

medieval_faires.done: currency.done feudalism.done
	@echo medieval_faires
	@type nul > medieval_faires.done

guilds: guilds.done

guilds.done: currency.done feudalism.done civil_service.done
	@echo guilds
	@type nul > guilds.done

mercantilism: mercantilism.done

mercantilism.done: currency.done humanism.done
	@echo mercantilism
	@type nul > mercantilism.done

stirrups: stirrups.done

stirrups.done: horseback_riding.done feudalism.done
	@echo stirrups
	@type nul > stirrups.done

mass_production: mass_production.done

mass_production.done: shipbuilding.done machinery.done education.done
	@echo mass_production
	@type nul > mass_production.done

naval_tradition: naval_tradition.done

naval_tradition.done: shipbuilding.done defensive_tactics.done
	@echo naval_tradition
	@type nul > naval_tradition.done

military_tactics: military_tactics.done

military_tactics.done: mathematics.done
	@echo military_tactics
	@type nul > military_tactics.done

education: education.done

education.done: mathematics.done apprenticeship.done
	@echo education
	@type nul > education.done

military_engineering: military_engineering.done

military_engineering.done: construction.done engineering.done
	@echo military_engineering
	@type nul > military_engineering.done

castles: castles.done

castles.done: construction.done divine_right.done exploration.done
	@echo castles
	@type nul > castles.done

games_recreation: games_recreation.done

games_recreation.done: construction.done state_workforce.done
	@echo games_recreation
	@type nul > games_recreation.done

gunpowder: gunpowder.done

gunpowder.done: apprenticeship.done stirrups.done military_engineering.done
	@echo gunpowder
	@type nul > gunpowder.done

printing: printing.done

printing.done: machinery.done education.done
	@echo printing
	@type nul > printing.done

metal_casting: metal_casting.done

metal_casting.done: machinery.done gunpowder.done
	@echo metal_casting
	@type nul > metal_casting.done

banking: banking.done

banking.done: education.done stirrups.done guilds.done
	@echo banking
	@type nul > banking.done

astronomy: astronomy.done

astronomy.done: education.done
	@echo astronomy
	@type nul > astronomy.done

military_science: military_science.done

military_science.done: stirrups.done printing.done siege_tactics.done
	@echo military_science
	@type nul > military_science.done

siege_tactics: siege_tactics.done

siege_tactics.done: castles.done metal_casting.done
	@echo siege_tactics
	@type nul > siege_tactics.done

square_rigging: square_rigging.done

square_rigging.done: cartography.done gunpowder.done
	@echo square_rigging
	@type nul > square_rigging.done

exploration: exploration.done

exploration.done: cartography.done mercenaries.done medieval_faires.done
	@echo exploration
	@type nul > exploration.done

industrialization: industrialization.done

industrialization.done: mass_production.done square_rigging.done
	@echo industrialization
	@type nul > industrialization.done

scientific_theory: scientific_theory.done

scientific_theory.done: banking.done astronomy.done the_enlightenment.done
	@echo scientific_theory
	@type nul > scientific_theory.done

colonialism: colonialism.done

colonialism.done: astronomy.done mercantilism.done
	@echo colonialism
	@type nul > colonialism.done

ballistics: ballistics.done

ballistics.done: metal_casting.done siege_tactics.done
	@echo ballistics
	@type nul > ballistics.done

economics: economics.done

economics.done: metal_casting.done scientific_theory.done
	@echo economics
	@type nul > economics.done

scorched_earth: scorched_earth.done

scorched_earth.done: metal_casting.done nationalism.done
	@echo scorched_earth
	@type nul > scorched_earth.done

steam_power: steam_power.done

steam_power.done: industrialization.done
	@echo steam_power
	@type nul > steam_power.done

flight: flight.done

flight.done: industrialization.done scientific_theory.done economics.done
	@echo flight
	@type nul > flight.done

steel: steel.done

steel.done: industrialization.done rifling.done
	@echo steel
	@type nul > steel.done

class_struggle: class_struggle.done

class_struggle.done: industrialization.done ideology.done
	@echo class_struggle
	@type nul > class_struggle.done

sanitation: sanitation.done

sanitation.done: scientific_theory.done urbanization.done
	@echo sanitation
	@type nul > sanitation.done

rifling: rifling.done

rifling.done: ballistics.done military_science.done
	@echo rifling
	@type nul > rifling.done

totalitarianism: totalitarianism.done

totalitarianism.done: military_science.done ideology.done
	@echo totalitarianism
	@type nul > totalitarianism.done

electricity: electricity.done

electricity.done: steam_power.done mercantilism.done
	@echo electricity
	@type nul > electricity.done

radio: radio.done

radio.done: steam_power.done flight.done conservation.done
	@echo radio
	@type nul > radio.done

chemistry: chemistry.done

chemistry.done: sanitation.done
	@echo chemistry
	@type nul > chemistry.done

suffrage: suffrage.done

suffrage.done: sanitation.done ideology.done
	@echo suffrage
	@type nul > suffrage.done

replaceable_parts: replaceable_parts.done

replaceable_parts.done: economics.done
	@echo replaceable_parts
	@type nul > replaceable_parts.done

capitalism: capitalism.done

capitalism.done: economics.done mass_media.done
	@echo capitalism
	@type nul > capitalism.done

combined_arms: combined_arms.done

combined_arms.done: flight.done combustion.done
	@echo combined_arms
	@type nul > combined_arms.done

synthetic_materials: synthetic_materials.done

synthetic_materials.done: flight.done plastics.done
	@echo synthetic_materials
	@type nul > synthetic_materials.done

rapid_deployment: rapid_deployment.done

rapid_deployment.done: flight.done cold_war.done
	@echo rapid_deployment
	@type nul > rapid_deployment.done

advanced_ballistics: advanced_ballistics.done

advanced_ballistics.done: replaceable_parts.done steel.done electricity.done
	@echo advanced_ballistics
	@type nul > advanced_ballistics.done

combustion: combustion.done

combustion.done: steel.done natural_history.done
	@echo combustion
	@type nul > combustion.done

computers: computers.done

computers.done: electricity.done radio.done suffrage.done totalitarianism.done class_struggle.done
	@echo computers
	@type nul > computers.done

advanced_flight: advanced_flight.done

advanced_flight.done: radio.done
	@echo advanced_flight
	@type nul > advanced_flight.done

rocketry: rocketry.done

rocketry.done: radio.done chemistry.done
	@echo rocketry
	@type nul > rocketry.done

nanotechnology: nanotechnology.done

nanotechnology.done: radio.done composites.done
	@echo nanotechnology
	@type nul > nanotechnology.done

mass_media: mass_media.done

mass_media.done: radio.done urbanization.done
	@echo mass_media
	@type nul > mass_media.done

nuclear_program: nuclear_program.done

nuclear_program.done: chemistry.done ideology.done
	@echo nuclear_program
	@type nul > nuclear_program.done

plastics: plastics.done

plastics.done: combustion.done
	@echo plastics
	@type nul > plastics.done

satellites: satellites.done

satellites.done: advanced_flight.done rocketry.done
	@echo satellites
	@type nul > satellites.done

globalization: globalization.done

globalization.done: advanced_flight.done rapid_deployment.done space_race.done
	@echo globalization
	@type nul > globalization.done

guidance_systems: guidance_systems.done

guidance_systems.done: rocketry.done advanced_ballistics.done
	@echo guidance_systems
	@type nul > guidance_systems.done

space_race: space_race.done

space_race.done: rocketry.done cold_war.done
	@echo space_race
	@type nul > space_race.done

nuclear_fission: nuclear_fission.done

nuclear_fission.done: advanced_ballistics.done combined_arms.done
	@echo nuclear_fission
	@type nul > nuclear_fission.done

telecommunications: telecommunications.done

telecommunications.done: computers.done
	@echo telecommunications
	@type nul > telecommunications.done

robotics: robotics.done

robotics.done: computers.done globalization.done
	@echo robotics
	@type nul > robotics.done

lasers: lasers.done

lasers.done: nuclear_fission.done
	@echo lasers
	@type nul > lasers.done

cold_war: cold_war.done

cold_war.done: nuclear_fission.done ideology.done
	@echo cold_war
	@type nul > cold_war.done

composites: composites.done

composites.done: synthetic_materials.done
	@echo composites
	@type nul > composites.done

stealth_technology: stealth_technology.done

stealth_technology.done: synthetic_materials.done
	@echo stealth_technology
	@type nul > stealth_technology.done

social_media: social_media.done

social_media.done: telecommunications.done professional_sports.done space_race.done
	@echo social_media
	@type nul > social_media.done

nuclear_fusion: nuclear_fusion.done

nuclear_fusion.done: lasers.done
	@echo nuclear_fusion
	@type nul > nuclear_fusion.done

code_of_laws: code_of_laws.done

code_of_laws.done: 
	@echo code_of_laws
	@type nul > code_of_laws.done

craftsmanship: craftsmanship.done

craftsmanship.done: code_of_laws.done
	@echo craftsmanship
	@type nul > craftsmanship.done

foreign_trade: foreign_trade.done

foreign_trade.done: code_of_laws.done
	@echo foreign_trade
	@type nul > foreign_trade.done

military_tradition: military_tradition.done

military_tradition.done: craftsmanship.done
	@echo military_tradition
	@type nul > military_tradition.done

early_empire: early_empire.done

early_empire.done: foreign_trade.done
	@echo early_empire
	@type nul > early_empire.done

mysticism: mysticism.done

mysticism.done: foreign_trade.done
	@echo mysticism
	@type nul > mysticism.done

political_philosophy: political_philosophy.done

political_philosophy.done: state_workforce.done early_empire.done
	@echo political_philosophy
	@type nul > political_philosophy.done

defensive_tactics: defensive_tactics.done

defensive_tactics.done: games_recreation.done political_philosophy.done
	@echo defensive_tactics
	@type nul > defensive_tactics.done

humanism: humanism.done

humanism.done: drama_poetry.done medieval_faires.done
	@echo humanism
	@type nul > humanism.done

mercenaries: mercenaries.done

mercenaries.done: military_training.done feudalism.done
	@echo mercenaries
	@type nul > mercenaries.done

feudalism: feudalism.done

feudalism.done: defensive_tactics.done
	@echo feudalism
	@type nul > feudalism.done

civil_service: civil_service.done

civil_service.done: defensive_tactics.done recorded_history.done
	@echo civil_service
	@type nul > civil_service.done

divine_right: divine_right.done

divine_right.done: theology.done civil_service.done
	@echo divine_right
	@type nul > divine_right.done

diplomatic_service: diplomatic_service.done

diplomatic_service.done: guilds.done
	@echo diplomatic_service
	@type nul > diplomatic_service.done

reformed_church: reformed_church.done

reformed_church.done: guilds.done divine_right.done
	@echo reformed_church
	@type nul > reformed_church.done

the_enlightenment: the_enlightenment.done

the_enlightenment.done: humanism.done diplomatic_service.done
	@echo the_enlightenment
	@type nul > the_enlightenment.done

civil_engineering: civil_engineering.done

civil_engineering.done: mercantilism.done
	@echo civil_engineering
	@type nul > civil_engineering.done

nationalism: nationalism.done

nationalism.done: the_enlightenment.done
	@echo nationalism
	@type nul > nationalism.done

opera_ballet: opera_ballet.done

opera_ballet.done: the_enlightenment.done
	@echo opera_ballet
	@type nul > opera_ballet.done

natural_history: natural_history.done

natural_history.done: colonialism.done
	@echo natural_history
	@type nul > natural_history.done

urbanization: urbanization.done

urbanization.done: civil_engineering.done nationalism.done
	@echo urbanization
	@type nul > urbanization.done

conservation: conservation.done

conservation.done: natural_history.done urbanization.done
	@echo conservation
	@type nul > conservation.done

mobilization: mobilization.done

mobilization.done: urbanization.done
	@echo mobilization
	@type nul > mobilization.done

cultural_heritage: cultural_heritage.done

cultural_heritage.done: conservation.done
	@echo cultural_heritage
	@type nul > cultural_heritage.done

ideology: ideology.done

ideology.done: mass_media.done mobilization.done
	@echo ideology
	@type nul > ideology.done

professional_sports: professional_sports.done

professional_sports.done: ideology.done
	@echo professional_sports
	@type nul > professional_sports.done

clean:
	@del /F *.done
